---
title: "zarz_ryzykiem_zadanie_1"
output: html_notebook
---



```{r}
#ladowanie pakietow

library(openxlsx)
library(PerformanceAnalytics)
library(e1071)
library(tidyr)

```

```{r}
#Wczytanie zbioru danych z pliku excel

zarz_ryz <- read.xlsx(xlsxFile = "01_nstacj_waluty_STACJONARNE.xlsx", 
                          sheet = "ceny walut", 
                          startRow = 1)

```

```{r}
#dostosowanie zbioru danych do dalszej analiy 

zarz_ryz <- zarz_ryz[-c(1:2),]      #usuwam wiersze 1 i 2
zarz_ryz <- as.data.frame(sapply(zarz_ryz, as.numeric))   #zmiana typu danych na numeric (ze wzgledu na pierwsze wiesze, cale kolumny ustawily sie jako zmienna tekstowa)
zarz_ryz$`data/waluta` <- as.Date(zarz_ryz$`data/waluta`,origin = "1900-01-01") #Ustawienie pierwszej kolumny jako typ danych "data"


#Wyciagniecie wszystkich walut i lat

waluty <- colnames(zarz_ryz[2:length(zarz_ryz)])

zarz_ryz_nd <- zarz_ryz[,-1]
zarz_ryz_sto_zw <- lapply(zarz_ryz_nd, Delt, k=1) 
zarz_ryz_sto_zw <- as.data.frame(zarz_ryz_sto_zw)
zarz_ryz_sto_zw <- cbind (zarz_ryz[,1],zarz_ryz_sto_zw)

daty <- unique(substring(zarz_ryz$`data/waluta`,1,4))
daty <- as.numeric(daty)



```

```{r}
#Miary zmiennosci 


var(zarz_ryz$USD)   #Wyliczenie wariancji 
sd(zarz_ryz$USD)    #Wyliczenie odchylenia standardowego 
(sd(zarz_ryz$USD)/mean(zarz_ryz$USD))*100   #Wyliczenie wsp????czynnika zmienno??ci
mad(zarz_ryz$USD, na.rm = TRUE)
DownsideDeviation(zarz_ryz$USD, MAR = mean(zarz_ryz$USD))

```

```{r}
#Miary ksztaltu rozkladu

skewness(zarz_ryz$USD, na.rm = TRUE, type = 1)
kurtosis(zarz_ryz$USD, na.rm = TRUE, type = 1)

```

```{r}
#Miary pozycyjne + srednia (ktora jest klasyczna)

summmm <- summary(zarz_ryz$USD) #Wyliczenie podstawowych cech statystyki opisowej
quantile(zarz_ryz$USD, c(.95, .99)) #Percentyl i kwantyl dla alfa 5 procent. 


```

